// Public functions verified in the V1 audit; visual language guided by the supplied screenshots.
export const VERTICALS = [
  { key: "formation", label: "Formation", icon: "graduation", accent: "#2458c6", soft: "#edf3ff", title: "Du parcours à la preuve.", text: "Sessions, stagiaires, documents et émargements : un environnement pensé pour les organismes de formation.", dashboard: "Pilotage de la formation", primary: "Créer une session", metrics: ["Sessions planifiées", "Stagiaires", "Dossiers à suivre", "Évaluations"], features: ["Sessions et stagiaires", "Émargement numérique", "Documents et preuves qualité"], nav: ["Pilotage", "Sessions", "Stagiaires", "Documents", "Évaluations"], actions: ["Préparer une session", "Suivre les émargements", "Réunir les documents"], modules: ["CRM et pipeline commercial", "Catalogue et programmes", "Sessions et émargements", "Évaluations automatisées", "Facturation et BPF", "Qualiopi et preuves"], path: "/logiciel-gestion-formation" },
  { key: "securite", label: "Sécurité privée", icon: "shield", accent: "#9b1c1c", soft: "#fff0f0", title: "Le bureau et le terrain, reliés.", text: "Agents, sites, vacations et rondes : une vision opérationnelle commune pour organiser et superviser la sécurité.", dashboard: "Supervision des opérations", primary: "Planifier une vacation", metrics: ["Vacations", "Agents", "Rondes", "Rapports"], features: ["Planning des vacations", "Rondes QR et main courante", "Supervision et alertes terrain"], nav: ["Supervision", "Agents", "Sites", "Vacations", "Main courante"], actions: ["Consulter les vacations", "Suivre les rondes QR", "Lire la main courante"], modules: ["Clients, sites et contrats", "Agents et agréments", "Planning et vacations", "Rondes QR et PTI", "Main courante terrain", "Facturation et portail client"], path: "/logiciel-securite-privee" },
  { key: "nettoyage", label: "Nettoyage", icon: "sparkles", accent: "#287451", soft: "#edf8f2", title: "Chaque prestation laisse une trace.", text: "Interventions, agents terrain et contrôles qualité : les prestations se planifient, se suivent et se documentent par site.", dashboard: "Pilotage de l’exploitation", primary: "Planifier une intervention", metrics: ["Interventions", "Agents terrain", "Avancement", "Contrôles qualité"], features: ["Interventions et pointage", "Rapports et photos avant/après", "Qualité et suivi des stocks"], nav: ["Exploitation", "Interventions", "Sites", "Qualité", "Stocks"], actions: ["Planifier les interventions", "Suivre les rapports", "Contrôler la qualité"], modules: ["Clients et sites", "Agents et affectations", "Pointage et consignes", "Rapports et anomalies", "Contrôles qualité", "Stocks et rentabilité"], path: "/logiciel-entreprise-nettoyage" },
  { key: "restauration", label: "Restauration", icon: "utensils", accent: "#94600e", soft: "#fff7e8", title: "Du couvert à la cuisine.", text: "Réservations, équipe, carte, hygiène et stocks : un environnement organisé autour du service et de l’exploitation du restaurant.", dashboard: "Pilotage du restaurant", primary: "Nouvelle réservation", metrics: ["Réservations", "Équipe planifiée", "Stocks", "Hygiène"], features: ["Réservations et plan de salle", "Carte et écran cuisine", "Hygiène et stocks"], nav: ["Restaurant", "Réservations", "Carte", "Cuisine", "Hygiène"], actions: ["Organiser le service", "Suivre la carte", "Consulter les contrôles"], modules: ["Réservations et plan de salle", "Carte et recettes", "Commandes et écran cuisine", "Planning des équipes", "Hygiène et traçabilité", "Stocks et pilotage"], path: "/logiciel-gestion-restaurant" },
  { key: "coiffure", label: "Coiffure & Beauté", icon: "scissors", accent: "#652052", soft: "#f8eff6", title: "Le rendez-vous au cœur du salon.", text: "Agenda, prestations, clients et collaborateurs : l’accueil et l’organisation du salon ou de l’institut restent au même endroit.", dashboard: "Votre salon, en un regard", primary: "Nouveau rendez-vous", metrics: ["Rendez-vous", "Clients", "Prestations", "Collaborateurs"], features: ["Agenda et réservation en ligne", "Prestations et collaborateurs", "Fichier client et fidélité"], nav: ["Salon", "Agenda", "Clients", "Prestations", "Équipe"], actions: ["Organiser les rendez-vous", "Retrouver les fiches clients", "Gérer les prestations"], modules: ["Réservation en ligne", "Planning du salon", "Fichier client", "Prestations et équipe", "Fidélité personnalisée", "Espace client"], path: "/logiciel-coiffure" },
] as const;
export const COMMON = ["Clients", "Équipes", "Planning", "Documents", "Pilotage", "Revenus selon l’activité"];
export function verticalStyle(index: number) {
  const v = VERTICALS[index];
  return { "--vertical-accent": v?.accent ?? "#25344b", "--vertical-soft": v?.soft ?? "#eef2f7", "--vertical-glow": `${v?.accent ?? "#61728c"}20` } as React.CSSProperties;
}
